object frmFundoContencao: TfrmFundoContencao
  Left = 0
  Top = 0
  Align = alClient
  AlphaBlend = True
  AlphaBlendValue = 100
  BorderStyle = bsNone
  Caption = 'frmFundoContencao'
  ClientHeight = 281
  ClientWidth = 543
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnClick = FormClick
  PixelsPerInch = 96
  TextHeight = 13
end
